### ISSUE TITLE
Parsing error?

### ISSUE THREAD

**Issue by manio** [0x20F/paris#42]
Hi,
I think i found some interesting thing in paris parser:
Recently I created a debug code which is doing a dumb colored debug with the following call:
```rust
info!("<black><----------------------------- before inner_get_ref</>");
```
As the result, the string is properly started in black, but the final resetting code `</>` is not interpreted (and printed instead).
I am thinking that probably the cause of the problem is this _"ascii-arrow"_: `<---------------------- `

I am OK if this is hard to fix for some reason, but I was only wanted to let you know about this... :)

**Comment by 0x20F** [comment]
Hi, thanks for letting me know!

Luckily it wasn't that hard to fix, opened up a PR for it and will look through it again a bit later today to make sure I've gotten everything right and nothing else is broken.

PR link: #43

**Comment by manio** [comment]
Oh, your're quick, thanks :)

**Comment by 0x20F** [comment]
Should be up on [crates.io](https://crates.io) too. 
Notice the version change to `1.5.9`.

**Comment by manio** [comment]
Thank you :)
