### ISSUE TITLE
Replace chrono with time due to security and maintenance issues

### ISSUE THREAD

**Issue by portno12** [0x20F/paris#47]
chrono maintenance and security history is shaky. currently a vuln has gone unacknowledged or fixed for a long time. see https://rustsec.org/advisories/RUSTSEC-2020-0159.html many projects are replacing chrono with time itself and newest version to avoid time vulns.

can this be done for the paris crate please?

**Comment by 0x20F** [comment]
Hi!

I'll look into it when I have a bit of time

**Comment by 0x20F** [comment]
Quick update: As per the #51 Pull Request, chrono isn't needed for the things that paris is actually using it for so it will be removed completely and replaced with the time module from the standard library.

Should be released soon enough in `1.5.13`
