### ISSUE TITLE
toggle formating on/off

### ISSUE THREAD

**Issue by jb-alvarado** [0x20F/paris#48]
**Is your feature request related to a problem? Please describe.**
I'm using simplelog with paris module for colourize the console output. But for logging to file, it would be nice to turn of the color format.
For simplelog it is way easer when paris already provide this feature. (https://github.com/Drakulix/simplelog.rs/issues/98)

**Describe the solution you'd like**
Add a toggle option, to turn on and off the formater.

**Describe alternatives you've considered**
I can strip the text messages with an regex, but is a bit ugly.

**Comment by 0x20F** [comment]
Hi!

What parts of paris are you using? Is it the `format`module and the `colorize_string` function?

I need a bit more detail on your specific usage of the package in order to figure out where the changes should be made, and if they are changes that can actually be made.

**Comment by jb-alvarado** [comment]
Hello 0x20F,

I hope I give you the right information, because I'm not to the developer of simplelog.

I think paris is only used in this macros: https://github.com/Drakulix/simplelog.rs/blob/master/src/paris_macros/mod.rs and the lines looks like:

```Rust
#[macro_export]
macro_rules! info {
    ($($args:tt)+) => {
        $crate::__private::log::info!("{}", $crate::__private::paris::formatter::colorize_string(format!($($args)*)));
    };
}
```

So, yes is the `colorize_string` function.

**Comment by 0x20F** [comment]
That looks alright, thank you!

I could add a new method that accepts a flag that tells it to only remove the tags and not replace them with ANSI codes although that's kind of as far as I can take it. Handling whether or not that flag should be true or false needs to be done in the `simplelog` crate.

Would that be enough for you guys?

**Comment by Drakulix** [comment]
Hey there :wave:, maintainer of simplelog here.

Yeah exactly, this is what we would need. simplelog already has configuration and that sort of flag would be enough to change the macro in a way that depending on the logger's config struct we could set that flag.

Thanks for the quick response!

**Comment by 0x20F** [comment]
Great!

I'll get to implementing it as soon as I have a bit of time.

**Comment by 0x20F** [comment]
Hi @Drakulix 

I've added a new method called `format_string` to the formatter module. 
If you could kindly test that it's what you need that would be great. If everything is ok I'll merge it and push it to `crates.io`.

Pull Request: https://github.com/0x20F/paris/pull/49
Branch: `optional-string-cleanup`

**Comment by 0x20F** [comment]
I'm going to assume everything is ok with this so it'll be merged, and hopefully released, today.

**Comment by jb-alvarado** [comment]
I could not test it together with simplelog, but from observing the code it looks exactly like I need it 🙂.

Thank you for your efforts!

**Comment by Drakulix** [comment]
> I'm going to assume everything is ok with this so it'll be merged, and hopefully released, today.

Sorry, I did not find time to test it, but I also don't expect any problems, so feel free to go ahead!
